import { Platform, StyleSheet } from 'react-native';

export const miraChatTokens = {
  color: {
    bgStart: '#F5F8FF',
    bgMid: '#EEF4FF',
    bgEnd: '#F6F1FF',
    surface: 'rgba(255,255,255,0.86)',
    surfaceSolid: '#FFFFFF',
    surfaceSoft: '#F7FAFF',
    border: 'rgba(99,122,255,0.14)',
    borderStrong: 'rgba(80,96,220,0.28)',
    primary: '#2837D8',
    primary2: '#4C6FFF',
    primary3: '#728BFF',
    cyan: '#38BDF8',
    mint: '#22C99A',
    mintSoft: '#DDFBF1',
    warning: '#FB923C',
    danger: '#EF6363',
    text: '#0B1B4D',
    textSoft: '#52638A',
    textMuted: '#8190B5',
  },
  fontFamily: Platform.select({
    web: '"IBM Plex Sans Thai", "Noto Sans Thai", "Prompt", "LINE Seed Sans TH", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    default: 'System',
  }),
};

const premiumShadow = {
  elevation: 8,
  shadowColor: '#253496',
  shadowOffset: { height: 18, width: 0 },
  shadowOpacity: 0.16,
  shadowRadius: 48,
};

const softShadow = {
  elevation: 4,
  shadowColor: '#253496',
  shadowOffset: { height: 10, width: 0 },
  shadowOpacity: 0.1,
  shadowRadius: 30,
};

export const miraChatStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  stage: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 18,
  },
  phoneShell: {
    backgroundColor: '#F7FAFF',
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 34,
    borderWidth: 1,
    maxWidth: 410,
    overflow: 'hidden',
    width: 390,
    ...premiumShadow,
  },
  phoneShellCompact: {
    borderRadius: 0,
    borderWidth: 0,
    maxWidth: undefined,
    width: '100%',
  },
  screen: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  sheenLayer: {
    bottom: 0,
    left: 0,
    opacity: 0.9,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  floatingGlassBand: {
    backgroundColor: 'rgba(255,255,255,0.48)',
    borderColor: 'rgba(255,255,255,0.65)',
    borderRadius: 42,
    borderWidth: 1,
    height: 150,
    left: -48,
    opacity: 0.44,
    position: 'absolute',
    right: -38,
    top: 118,
    transform: [{ rotate: '-8deg' }],
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 10,
    zIndex: 5,
  },
  glassCircleButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
    ...softShadow,
  },
  glassCircleButtonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.97 }],
  },
  headerCenter: {
    alignItems: 'center',
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  headerTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 24,
  },
  headerStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 2,
  },
  headerStatusDot: {
    backgroundColor: miraChatTokens.color.mint,
    borderColor: '#FFFFFF',
    borderRadius: 999,
    borderWidth: 1,
    height: 8,
    width: 8,
  },
  headerLogoImage: {
    height: 26,
    width: 128,
  },
  headerStatusDotMuted: {
    backgroundColor: miraChatTokens.color.textMuted,
  },
  headerStatusText: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 15,
  },
  authPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 58,
    paddingHorizontal: 12,
    ...softShadow,
  },
  authPillLive: {
    backgroundColor: miraChatTokens.color.mintSoft,
    borderColor: 'rgba(34,201,154,0.28)',
  },
  authPillPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  authPillText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 15,
  },
  scroll: {
    flex: 1,
    marginTop: 8,
  },
  scrollContent: {
    gap: 12,
    paddingBottom: 132,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  brandPanel: {
    gap: 10,
    paddingTop: 2,
  },
  brandEyebrow: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  brandTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  brandTitle: {
    color: miraChatTokens.color.text,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 31,
  },
  smartBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.1)',
    borderColor: 'rgba(76,111,255,0.18)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 11,
  },
  smartBadgeText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  greetingCard: {
    backgroundColor: miraChatTokens.color.surface,
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 14,
    ...premiumShadow,
  },
  greetingHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  greetingLogoImage: {
    height: 32,
    width: 104,
  },
  orbFrame: {
    alignItems: 'center',
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  orbGlow: {
    backgroundColor: 'rgba(91,115,255,0.22)',
    borderRadius: 999,
    height: 58,
    position: 'absolute',
    width: 58,
  },
  orbSvg: {
    borderRadius: 999,
  },
  greetingCopy: {
    flex: 1,
    minWidth: 0,
  },
  greetingTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
  },
  greetingText: {
    color: miraChatTokens.color.text,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15.5,
    fontWeight: '800',
    lineHeight: 22,
  },
  trustRow: {
    flexDirection: 'row',
    gap: 8,
  },
  trustItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(247,250,255,0.86)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 70,
    paddingHorizontal: 7,
    paddingVertical: 9,
  },
  trustIcon: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(76,111,255,0.12)',
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  trustText: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '800',
    lineHeight: 15,
    textAlign: 'center',
  },
  quickReplies: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  chip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 36,
    paddingHorizontal: 14,
    ...softShadow,
  },
  chipPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  chipText: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13.2,
    fontWeight: '800',
    lineHeight: 17,
  },
  flowProgress: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    padding: 13,
    ...softShadow,
  },
  flowProgressTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 17,
  },
  flowSteps: {
    flexDirection: 'row',
    gap: 7,
  },
  flowStep: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
  },
  flowStepDot: {
    alignItems: 'center',
    backgroundColor: 'rgba(82,99,138,0.08)',
    borderColor: 'rgba(82,99,138,0.12)',
    borderRadius: 999,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  flowStepDotActive: {
    backgroundColor: 'rgba(76,111,255,0.14)',
    borderColor: 'rgba(76,111,255,0.28)',
  },
  flowStepLabel: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 10.5,
    fontWeight: '800',
    lineHeight: 13,
    textAlign: 'center',
  },
  flowStepLabelActive: {
    color: miraChatTokens.color.primary,
  },
  assistantRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 9,
    maxWidth: '100%',
  },
  assistantAvatar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(76,111,255,0.16)',
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    marginTop: 4,
    width: 34,
    ...softShadow,
  },
  assistantLogoMark: {
    height: 22,
    width: 22,
  },
  assistantStack: {
    flex: 1,
    gap: 10,
    maxWidth: 310,
    minWidth: 0,
  },
  assistantBubble: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(255,255,255,0.98)',
    borderRadius: 22,
    borderTopLeftRadius: 9,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...softShadow,
  },
  assistantText: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15.5,
    fontWeight: '600',
    lineHeight: 23,
  },
  userRow: {
    alignSelf: 'flex-end',
    maxWidth: '84%',
  },
  userBubble: {
    borderColor: 'rgba(255,255,255,0.62)',
    borderRadius: 22,
    borderTopRightRadius: 9,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 15,
    paddingVertical: 11,
    ...softShadow,
  },
  userText: {
    color: '#FFFFFF',
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15.5,
    fontWeight: '700',
    lineHeight: 22,
  },
  systemRow: {
    alignItems: 'center',
  },
  systemBubble: {
    backgroundColor: 'rgba(221,251,241,0.84)',
    borderColor: 'rgba(34,201,154,0.24)',
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: '92%',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  systemText: {
    color: '#0D6A55',
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12.5,
    fontWeight: '800',
    lineHeight: 17,
    textAlign: 'center',
  },
  timestamp: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
    marginTop: 5,
  },
  timestampUser: {
    alignSelf: 'flex-end',
    marginRight: 4,
  },
  typingBubble: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 36,
    paddingHorizontal: 14,
    ...softShadow,
  },
  typingDot: {
    backgroundColor: miraChatTokens.color.primary2,
    borderRadius: 999,
    height: 6,
    width: 6,
  },
  commerceCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(255,255,255,0.98)',
    borderRadius: 26,
    borderWidth: 1,
    gap: 12,
    padding: 13,
    ...premiumShadow,
  },
  commerceHeader: {
    gap: 3,
  },
  commerceEyebrow: {
    color: miraChatTokens.color.primary2,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 15,
  },
  commerceTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
  },
  packageGrid: {
    gap: 12,
  },
  packageCard: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 11,
    overflow: 'hidden',
    padding: 12,
    ...softShadow,
  },
  packageCardRecommended: {
    borderColor: miraChatTokens.color.borderStrong,
  },
  packageHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
  },
  packageMedia: {
    alignItems: 'center',
    backgroundColor: miraChatTokens.color.surfaceSoft,
    borderColor: 'rgba(76,111,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    height: 76,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 76,
  },
  packageImage: {
    height: '100%',
    width: '100%',
  },
  packageCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  packageBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.1)',
    borderColor: 'rgba(76,111,255,0.16)',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 24,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeMint: {
    backgroundColor: miraChatTokens.color.mintSoft,
    borderColor: 'rgba(34,201,154,0.24)',
  },
  badgeText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 14,
  },
  badgeMintText: {
    color: '#0B7A62',
  },
  packageTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15.5,
    fontWeight: '900',
    lineHeight: 20,
  },
  packageDescription: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
  },
  packageIncludes: {
    gap: 6,
  },
  includeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 7,
  },
  includeDot: {
    backgroundColor: miraChatTokens.color.cyan,
    borderRadius: 999,
    height: 6,
    marginTop: 7,
    width: 6,
  },
  includeText: {
    color: miraChatTokens.color.textSoft,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12.5,
    fontWeight: '700',
    lineHeight: 18,
  },
  packageFooter: {
    alignItems: 'center',
    borderTopColor: 'rgba(99,122,255,0.1)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingTop: 11,
  },
  packagePrice: {
    color: miraChatTokens.color.text,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 29,
  },
  packageMeta: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 1,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 100,
    overflow: 'hidden',
    paddingHorizontal: 14,
    ...softShadow,
  },
  primaryButtonDisabled: {
    opacity: 0.52,
  },
  primaryButtonPressed: {
    opacity: 0.84,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 18,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.08)',
    borderColor: 'rgba(76,111,255,0.14)',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  categoryPressable: {
    flexGrow: 1,
    width: '47%',
  },
  categoryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 112,
    padding: 12,
    width: '100%',
    ...softShadow,
  },
  categoryCardPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  categoryIconCircle: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.1)',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    marginBottom: 9,
    width: 34,
  },
  categoryTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 17,
  },
  categoryMeta: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 5,
  },
  branchCard: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  branchRow: {
    alignItems: 'center',
    backgroundColor: miraChatTokens.color.surfaceSoft,
    borderColor: 'rgba(99,122,255,0.1)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 54,
    paddingHorizontal: 10,
  },
  branchNumber: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.12)',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  branchNumberText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '900',
  },
  branchCopy: {
    flex: 1,
    minWidth: 0,
  },
  branchName: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 17,
  },
  branchMeta: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 2,
  },
  branchAction: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '900',
  },
  orderPanel: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: 'rgba(255,255,255,0.98)',
    borderRadius: 26,
    borderWidth: 1,
    gap: 13,
    padding: 14,
    ...premiumShadow,
  },
  orderHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  orderCopy: {
    flex: 1,
    minWidth: 0,
  },
  orderEyebrow: {
    color: miraChatTokens.color.primary2,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 15,
  },
  orderTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
    marginTop: 3,
  },
  orderMeta: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12.5,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 4,
  },
  statusPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.1)',
    borderColor: 'rgba(76,111,255,0.18)',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 30,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillMint: {
    backgroundColor: miraChatTokens.color.mintSoft,
    borderColor: 'rgba(34,201,154,0.25)',
  },
  statusPillWarning: {
    backgroundColor: 'rgba(251,146,60,0.13)',
    borderColor: 'rgba(251,146,60,0.24)',
  },
  statusPillText: {
    color: miraChatTokens.color.primary,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '900',
    lineHeight: 14,
  },
  statusPillMintText: {
    color: '#0B7A62',
  },
  orderSteps: {
    flexDirection: 'row',
    gap: 7,
  },
  orderStepItem: {
    flex: 1,
    gap: 6,
  },
  orderStepBar: {
    backgroundColor: 'rgba(82,99,138,0.13)',
    borderRadius: 999,
    height: 5,
    overflow: 'hidden',
  },
  orderStepBarActive: {
    backgroundColor: miraChatTokens.color.primary2,
    flex: 1,
  },
  orderStepLabel: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
  },
  orderStepLabelActive: {
    color: miraChatTokens.color.primary,
  },
  orderHint: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  formFields: {
    gap: 10,
  },
  formRow: {
    flexDirection: 'row',
    gap: 9,
  },
  formField: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  formFieldSmall: {
    width: 82,
  },
  formLabel: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 15,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 15,
    borderWidth: 1,
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 14,
    fontWeight: '700',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 0,
  },
  dateButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 52,
    paddingHorizontal: 12,
  },
  dateButtonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  dateButtonTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13.5,
    fontWeight: '900',
    lineHeight: 17,
  },
  dateButtonMeta: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11.5,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 2,
  },
  chevronText: {
    color: miraChatTokens.color.primary2,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  calendarPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    padding: 12,
    ...softShadow,
  },
  calendarHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15,
    fontWeight: '900',
  },
  calendarNav: {
    flexDirection: 'row',
    gap: 7,
  },
  calendarNavButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(76,111,255,0.1)',
    borderRadius: 999,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  calendarWeekRow: {
    flexDirection: 'row',
  },
  calendarWeekday: {
    color: miraChatTokens.color.textMuted,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 14,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 4,
  },
  calendarCellWrap: {
    width: '14.285%',
  },
  calendarCell: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: '100%',
  },
  calendarCellInRange: {
    backgroundColor: 'rgba(76,111,255,0.1)',
  },
  calendarCellSelected: {
    backgroundColor: miraChatTokens.color.primary2,
    borderRadius: 9,
  },
  calendarDateText: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  calendarDateTextSelected: {
    color: '#FFFFFF',
  },
  timeSlotRow: {
    flexDirection: 'row',
    gap: 8,
  },
  timeSlotPressable: {
    flex: 1,
  },
  timeSlotButton: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 17,
    borderWidth: 1,
    flex: 1,
    minHeight: 56,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  timeSlotButtonSelected: {
    backgroundColor: miraChatTokens.color.primary2,
    borderColor: miraChatTokens.color.primary2,
  },
  timeSlotLabel: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 17,
  },
  timeSlotDetail: {
    color: miraChatTokens.color.textMuted,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    marginTop: 2,
  },
  timeSlotSelectedText: {
    color: '#FFFFFF',
  },
  formError: {
    color: miraChatTokens.color.danger,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  paymentCard: {
    alignItems: 'center',
    backgroundColor: miraChatTokens.color.surfaceSoft,
    borderColor: miraChatTokens.color.border,
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  qrFrame: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11,27,77,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    padding: 10,
  },
  paymentTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'center',
  },
  paymentMeta: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12.5,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  paymentError: {
    color: miraChatTokens.color.danger,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
    textAlign: 'center',
  },
  loadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 34,
  },
  loadingText: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12.5,
    fontWeight: '800',
  },
  orderStatusRow: {
    backgroundColor: '#FFFFFF',
    borderColor: miraChatTokens.color.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 11,
  },
  memoryCard: {
    backgroundColor: miraChatTokens.color.mintSoft,
    borderColor: 'rgba(34,201,154,0.2)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 3,
    padding: 12,
  },
  memoryTitle: {
    color: '#0B7A62',
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '900',
  },
  memoryText: {
    color: '#0D6A55',
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  inputWrap: {
    bottom: 0,
    left: 0,
    paddingBottom: 10,
    paddingHorizontal: 14,
    position: 'absolute',
    right: 0,
    zIndex: 10,
  },
  voiceStatus: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    marginBottom: 8,
    maxWidth: '100%',
    paddingHorizontal: 11,
    paddingVertical: 7,
    ...softShadow,
  },
  voiceStatusDot: {
    backgroundColor: miraChatTokens.color.warning,
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  voiceStatusText: {
    color: miraChatTokens.color.textSoft,
    flexShrink: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 15,
  },
  inputBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 26,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 60,
    paddingHorizontal: 8,
    paddingVertical: 7,
    ...premiumShadow,
  },
  inputIconButton: {
    alignItems: 'center',
    backgroundColor: miraChatTokens.color.surfaceSoft,
    borderColor: miraChatTokens.color.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  inputIconButtonDisabled: {
    opacity: 0.55,
  },
  composerInput: {
    color: miraChatTokens.color.text,
    flex: 1,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15,
    fontWeight: '700',
    minHeight: 44,
    paddingHorizontal: 2,
    paddingVertical: 0,
  },
  sendButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 46,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 46,
    ...softShadow,
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  homeIndicator: {
    alignSelf: 'center',
    backgroundColor: 'rgba(11,27,77,0.18)',
    borderRadius: 999,
    height: 4,
    marginTop: 10,
    width: 92,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: miraChatTokens.color.border,
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  emptyStateTitle: {
    color: miraChatTokens.color.text,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyStateText: {
    color: miraChatTokens.color.textSoft,
    fontFamily: miraChatTokens.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
});
