import { deriveSelfProvisionName, handleReferralSelfProvision } from '../referralSelfProvision.ts';
import { HttpError } from '../http.ts';
import type { ReferralSelfProvisionContext, ReferralSelfProvisionDeps } from '../referralSelfProvision.ts';
import type { ReferrerRow, TenantRow } from '../types.ts';

declare const Deno: {
  test: (name: string, fn: () => void | Promise<void>) => void;
};

function assertEquals<T>(actual: T, expected: T) {
  if (actual !== expected) {
    throw new Error(`Expected ${expected}, got ${actual}`);
  }
}

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(message);
  }
}

async function assertHttpError(fn: () => Promise<unknown>, code: string, status: number) {
  try {
    await fn();
  } catch (error) {
    if (!(error instanceof HttpError)) {
      throw new Error('Expected HttpError.');
    }

    assertEquals(error.code, code);
    assertEquals(error.status, status);
    return;
  }

  throw new Error('Expected request to fail.');
}

const tenant: TenantRow = {
  attribution_window_days: 30,
  display_name: 'Mira Hospital',
  features: {},
  id: 'tenant-1',
  logo_url: null,
  promptpay_id: null,
  slug: 'demo-hospital',
};
const context: ReferralSelfProvisionContext = {
  authEmail: 'doctor.one@example.com',
  authUserId: 'auth-user-1',
  tenant,
};

function referrer(overrides: Partial<ReferrerRow> = {}): ReferrerRow {
  return {
    active: true,
    auth_user_id: context.authUserId,
    commission_scheme: {
      by_category: {},
      default: 10,
      mode: 'percent',
    },
    created_at: '2026-06-15T00:00:00.000Z',
    id: 'referrer-1',
    name: 'Doctor One',
    phone: null,
    ref_code: 'DRAB12',
    tenant_id: tenant.id,
    type: 'staff',
    ...overrides,
  };
}

function createDeps(options: {
  existing?: ReferrerRow | null;
  isMember?: boolean;
  profileName?: string | null;
} = {}) {
  const inserts: Record<string, unknown>[] = [];
  const deps: ReferralSelfProvisionDeps = {
    insertReferrer: async (tenantId, authUserId, name) => {
      inserts.push({
        active: true,
        auth_user_id: authUserId,
        name,
        tenant_id: tenantId,
        type: 'staff',
      });

      return referrer({
        auth_user_id: authUserId,
        name,
        tenant_id: tenantId,
      });
    },
    loadExistingReferrer: async () => options.existing ?? null,
    loadMember: async () => (options.isMember === false ? null : { role: 'tenant_staff' }),
    loadProfileName: async () => options.profileName ?? null,
  };

  return {
    deps,
    inserts,
  };
}

Deno.test('deriveSelfProvisionName prefers profile display name', () => {
  assertEquals(deriveSelfProvisionName('  Dr   One  ', 'doctor.one@example.com'), 'Dr One');
});

Deno.test('deriveSelfProvisionName falls back to email handle and final default', () => {
  assertEquals(deriveSelfProvisionName(null, 'doctor.one@example.com'), 'doctor one');
  assertEquals(deriveSelfProvisionName(null, null), 'Staff referrer');
});

Deno.test('referral self-provision rejects non-members', async () => {
  const { deps } = createDeps({ isMember: false });

  await assertHttpError(
    () => handleReferralSelfProvision({ tenant_slug: tenant.slug }, context, deps),
    'VALIDATION',
    403,
  );
});

Deno.test('referral self-provision creates a staff referrer with DB-generated defaults', async () => {
  const { deps, inserts } = createDeps({ profileName: 'พญ. หนึ่ง' });
  const response = await handleReferralSelfProvision({ tenant_slug: tenant.slug }, context, deps);

  assertEquals(response.created, true);
  assertEquals(response.ref_code, 'DRAB12');
  assertEquals(response.referrer_id, 'referrer-1');
  assertEquals(inserts.length, 1);
  assertEquals(inserts[0].name, 'พญ. หนึ่ง');
  assertEquals(inserts[0].type, 'staff');
  assertEquals(inserts[0].active, true);
  assert(!('commission_scheme' in inserts[0]), 'expected commission_scheme to be omitted for DB default');
  assert(!('ref_code' in inserts[0]), 'expected ref_code to be generated by the DB trigger');
});

Deno.test('referral self-provision returns an existing referrer idempotently', async () => {
  const { deps, inserts } = createDeps({ existing: referrer({ id: 'existing-referrer', ref_code: 'EXST12' }) });
  const response = await handleReferralSelfProvision({ tenant_slug: tenant.slug }, context, deps);

  assertEquals(response.created, false);
  assertEquals(response.ref_code, 'EXST12');
  assertEquals(response.referrer_id, 'existing-referrer');
  assertEquals(inserts.length, 0);
});
